# Generated by Django 6.0 on 2025-12-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mercado_pago_subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
