# Generated by Django 6.0 on 2025-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='external_reference',
            field=models.CharField(help_text='ID do plano no Mercado Pago', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recurrence',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20),
        ),
    ]
