# Generated by Django 6.0 on 2025-12-13 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_active_alter_plan_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='has_ai',
            field=models.BooleanField(default=True, help_text='Define se o plano tem acesso às fun~~oes de IA'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_posts',
            field=models.IntegerField(default=100, help_text='Quantidade máxima de conteúdos gerados por período'),
        ),
    ]
