# Generated by Django 6.0 on 2025-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_created_at_plan_has_ai_plan_max_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='has_ai',
            field=models.BooleanField(default=True, help_text='Define se o plano tem acesso às funções de IA'),
        ),
    ]
