# Generated by Django 6.0 on 2025-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_contenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('past_due', 'Pagamento atrasado'), ('canceled', 'Cancelada')], default='trial', max_length=20),
        ),
    ]
