# Generated by Django 6.0 on 2025-12-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_subscription_status'),
        ('billing', '0010_seed_plans'),
    ]

    operations = [
    ]
